name: CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'Python_interface'
  pull_request:
    branches:
      - main
    paths:
      - 'Python_interface'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up PYTHONPATH
        run: echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)" >> $GITHUB_ENV
          
      - name: Set up Python (if needed)
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest Python_interface
   #       run: |
  #        export PYTHONPATH=$PYTHONPATH:$(pwd)/Python_interface
  #        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/Python_interface
          
